sudo: false
language: node_js
node_js:
  - iojs
  - '0.12'
  - '0.10'
services: mongodb
matrix:
  allow_failures:
    - node_js: iojs
env:
  - TEST_DIR=client
  - TEST_DIR=server
script: cd $TEST_DIR && npm install && npm test