sudo: false
language: node_js
node_js:
  - iojs
  - '0.12'
  - '0.10'
services: mongodb
matrix:
  allow_failures:
    - node_js: iojs
script: cd server && ./generateconfigfile.sh && npm install && npm test